feat: Add ams rdvp
berty/berty pull request #2437
Opened 2020-10-08 09:18 UTC by gfanton

- Add announce argument to rdvp server
- Add new rdvp endpoint:
```
$ madns /dnsaddr/rdvp.berty.io/ipfs/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ
/ip4/51.15.25.224/udp/4040/quic/p2p/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ
/ip4/51.15.25.224/tcp/4040/p2p/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ
```

2020-10-08 09:21 UTC, Jorropo approved these changes
LGTM

2020-10-08 09:23 UTC, Jorropo approved these changes
LGTM

2020-10-08 16:18 UTC, Jorropo commented on go/internal/config/berty.go
> +		"/dnsaddr/rdvp.berty.io/ipfs/12D3KooWHhDBv6DJJ4XDWjzEXq6sVNEs6VuxsV1WyBBEhPENHzcZ",
Rebase and use IPs, not dns addr (you can copy the mobile config).

2020-10-08 16:18 UTC, Jorropo requested changes
not dns addr

2020-10-09 13:16 UTC, Jorropo approved these changes
LGTM (tested, works fine)

2020-10-09 13:42 UTC, moul approved these changes

2020-10-09 13:53 UTC, merged