WIP: chore: cleanup buildkite and project
berty/berty pull request #2456
Opened 2020-10-09 21:54 UTC by aeddi

2020-10-10 09:42 UTC, moul commented on js/README.md
>  ```shell
```suggestion
```console
```

2020-10-10 09:43 UTC, moul commented on js/README.md
> +make ios.debug
```suggestion
$ make ios.debug
```

2020-10-13 07:23 UTC, Jorropo requested changes

2020-10-13 07:23 UTC, Jorropo commented on js/README.md
> +$ BERTY_DAEMON_PORT=1337 make.daemon
```suggestion
$ BERTY_DAEMON_PORT=1337 make daemon.start
```

2020-10-13 07:28 UTC, aeddi commented on js/README.md
> +$ BERTY_DAEMON_PORT=1337 make.daemon
Thanks ;)

2020-10-13 07:33 UTC, Jorropo approved these changes
SGTM

2020-10-13 09:05 UTC, moul approved these changes

2020-10-13 11:34 UTC, merged