fix: ipfs relay
berty/berty pull request #2742
Opened 2020-11-18 15:36 UTC by gfanton

2020-11-19 14:08 UTC, Jorropo requested changes

2020-11-19 14:08 UTC, Jorropo commented on go/internal/initutil/ipfs.go
> +
```suggestion
		}

```

2020-11-19 14:08 UTC, Jorropo commented on go/internal/initutil/ipfs.go
```suggestion

		{
```

2022-03-16 09:04 UTC, gfanton commented
Outdated

2022-03-16 09:04 UTC, closed without merging