[WIP] chore: cleanup assets and iOS projects
berty/berty pull request #3021
Opened 2021-01-21 11:15 UTC by aeddi

Fixes #2835

2021-01-21 17:36 UTC, moul approved these changes

2021-01-21 17:41 UTC, n0izn0iz requested changes
lgtm except comment

2021-01-21 17:41 UTC, n0izn0iz commented on js/ios/berty.yaml
> +    - path: ../assets/font
we need to adjust the makefile deps too

2021-01-21 18:57 UTC, aeddi commented on js/ios/berty.yaml
> +    - path: ../assets/font
Yes you're right, I'll add this deps

2021-01-21 20:10 UTC, n0izn0iz approved these changes
`js/assets` feels duplicate with `js/packages/assets`
I'm for putting stuff in `js/packages/assets` so we can import them in js code with `@berty-tech/assets` and keep the same structure as for the other js importables

2021-01-22 09:10 UTC, aeddi commented
> `js/assets` feels duplicate with `js/packages/assets`
> I'm for putting stuff in `js/packages/assets` so we can import them in js code with `@berty-tech/assets` and keep the same structure as for the other js importables

Okay, as long as it's cleaner, I'm fine with it 👍 
You'll do this in another PR if I understand correctly, I'll merge this one.

2021-01-22 09:10 UTC, merged