feat: add tool to check unused exports
berty/berty pull request #4053
Opened 2022-04-07 08:54 UTC by clegirar

Signed-off-by: clegirar <clemntgirard@gmail.com>

2022-04-14 09:02 UTC, n0izn0iz requested changes

2022-04-14 09:02 UTC, n0izn0iz commented on js/packages/store/index.ts
> -export * from './utils'
why rewrite the imports?

2022-04-14 09:22 UTC, moul commented
loving this PR <3 :)

2022-04-15 08:20 UTC, n0izn0iz approved these changes

2022-04-15 08:21 UTC, merged