fix: long usernames exceeds the username box
berty/berty pull request #4647
Opened 2023-03-29 14:30 UTC by iuricmp

- make the username box flexible to fit long names

![Screenshot_20230329_152438_Berty Debug](https://user-images.githubusercontent.com/689440/228572442-27816539-ad35-4b00-b618-fe3c8b23e228.jpg)

- also fit short names

![Screenshot_20230329_152414_Berty Debug](https://user-images.githubusercontent.com/689440/228572491-d699a24d-e396-45b9-87fc-686ff8c3a4f9.jpg)

2023-03-29 14:38 UTC, D4ryl00 commented
Have you set a size limit for the username box?
What happens if your username is 1000 characters long?

2023-04-05 13:30 UTC, clegirar requested changes

2023-04-05 13:30 UTC, clegirar commented on js/packages/screens/settings/SettingsHome/SettingsHome.tsx
> +								{
Same here, you can create a `Stylesheet` object at the bottom of the file 👍

2023-04-19 12:47 UTC, clegirar approved these changes
LGTM 👍

2023-04-19 12:50 UTC, merged